---
#import GPG
rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

# Add Repo /etc/yum.repos.d/elasticsearch.repo
[elasticsearch]
name=Elasticsearch repository for 8.x packages
baseurl=https://artifacts.elastic.co/packages/8.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=0
autorefresh=1
type=rpm-md

# restart daemon
# install elasticseatrch en output naar file
sudo dnf install --enablerepo=elasticsearch elasticsearch | tee > /tmp/elastic-install.log 
The generated password for the elastic built-in superuser is : CH77_qG8ji8QCxwUCr3w

